# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 1999 - 2006 Intel Corporation.
# Copyright(c) 2022 - 2022 Allen He

#
# Makefile for the Intel(R) PRO/1000 ethernet driver
#

DRIVER = e1000
objs = e1000_main.obj e1000_hw.obj e1000_ethtool.obj e1000_param.obj

#obj-$(CONFIG_E1000) += e1000.o
include ../ndriver_make.txt